#index:
#    path: /
#    controller: App\Controller\DefaultController::index
_posbundle:
  resource: '@FlexyPOSBundle/Resources/config/routes.yaml'
  prefix: /
_billards:
  resource: '@FlexyBillardsBundle/Resources/config/routes.yaml'
  prefix: /
